#!/bin/bash

../../../vendor/bin/propel reverse --database-name="oimovel"  "pgsql:host=localhost;dbname=oimovel;user=oimovel;password=oimovel" --output-dir="."
../../../vendor/bin/propel model:build  --output-dir="../../models/propel"

../../../artisan dump-autoload
