# An example of Propel configuration file in yaml
propel:
  database:
      connections:
          mysource:
              adapter: pgsql
              classname: Propel\Runtime\Connection\DebugPDO
              dsn: pgsql:host=localhost;dbname=oimovel
              user: oimovel
              password: oimovel
  runtime:
      defaultConnection: mysource
      connections:
          - mysource
  generator:
      defaultConnection: mysource
      connections:
          - mysource
